### ISSUE TITLE
Problem starting up the app 

### ISSUE THREAD

**Issue by nicolas-droulers** [kishorv06/ChromePad#1]
Chromes os version: 76.0.3789.0 (dev build) 32 bits
Python version: Python 2.7.15
When running the sudo chromepad command I get the following error: 

Traceback (most recent call last):
  File "/usr/local/bin/GamePad.py", line 17, in <module>
    in_file = open(infile_path, "rb")
IOError: [Errno 21] Is a directory: '/dev/input/'

**Comment by kishorviswanathan** [comment]
Looks like the script is unable to find the path of your keyboard. Try finding the path manually and edit line 10 of GamePad.py. The path should look like /dev/input/event*. For me it is /dev/input/event3.
